services:
  ollama:
    image: ollama/ollama:latest
    platform: ${PLATFORM:-linux/amd64}
    ports:
      - "${PORT:-11434}:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*

volumes:
  ollama:
